name: brainvox
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - numpy>=1.24
  - pandas>=2.2
  - nibabel>=5.1
  - scikit-learn>=1.3
  - scipy>=1.11
  - matplotlib>=3.8
  - tqdm>=4.66
  - tensorboard>=2.15
  - openpyxl>=3.1
  - pip
